name: CI
'on':
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
jobs:
  Lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: akx/pre-commit-uv-action@v0.1.0
